spring.application.name=spring-security-jwt

# application.properties
server.port=8081

#no need to set here because  we are setting cradential by code
#spring.security.user.password=raees1234
#spring.security.user.name=raees
